obj-$(CONFIG_LNX_MOD_32BIT)       += linux_mods/i386/
#obj-$(CONFIG_LNX_MOD_64BIT)       += linux_mods/x86_64/
obj-$(CONFIG_V3_MOD_32BIT)       += v3_mods/i386/
#obj-$(CONFIG_V3_MOD_64BIT)       += v3_mods/x86_64/
