#ifndef __vmm_sizes
#define __vmm_sizes
#define KERNEL_LOAD_ADDRESS  0x3ff9d000
#define KERNEL_SETUP_LENGTH ( 1 *512)
#define KERNEL_CORE_LENGTH ( 203 *512)
#define KERNEL_START (KERNEL_LOAD_ADDRESS)
#define KERNEL_END (KERNEL_LOAD_ADDRESS+KERNEL_CORE_LENGTH-1)
#define BIOS_LENGTH ( 128 *512)
#define VGA_BIOS_LENGTH ( 55 *512)
#define VMXASSIST_LENGTH ( 41 *512)
#define BIOS_START (KERNEL_LOAD_ADDRESS+KERNEL_CORE_LENGTH)
#define VGA_BIOS_START (BIOS_START+BIOS_LENGTH)
#define VMXASSIST_START (VGA_BIOS_START+VGA_BIOS_LENGTH)
//Note this is a second copy of the rom bios for debug
#define BIOS2_START (VMXASSIST_START+VMXASSIST_LENGTH)
#define VM_BOOT_PACKAGE_START (BIOS_START) 
#define VM_BOOT_PACKAGE_END  (BIOS2_START+BIOS_LENGTH-1) 
#endif
