# ==========================================================================
# Build system
# ==========================================================================

# -mpreferred-stack-boundary=2 is essential in preventing gcc 4.2.x
# from aligning stack to 16 bytes. (Which is gcc's way of supporting SSE).
CFLAGS += $(call cc-option,-m32,) -D__V3_32BIT__
AFLAGS += $(call cc-option,-m32,) -D__V3_32BIT__
LDFLAGS += -melf_i386
