obj-$(V3_CONFIG_SHADOW_PAGING_VTLB) += vmm_shdw_pg_tlb.o
obj-$(V3_CONFIG_SWAPBYPASS) += vmm_shdw_pg_swapbypass.o
obj-$(V3_CONFIG_SHADOW_PAGING_CACHE) += vmm_shdw_pg_cache.o


#obj-$(V3_CONFIG_SHADOW_PAGING_KVM) += vmm_shdw_pg_kvm.o
