obj-$(V3_CONFIG_EXT_SW_INTERRUPTS) += ext_sw_intr.o
obj-$(V3_CONFIG_EXT_SYSCALL_HIJACK) += ext_syscall_hijack.o
obj-$(V3_CONFIG_EXT_EXECVE_HOOK) += ext_execve_hook.o
obj-$(V3_CONFIG_EXT_EXECVE_HOOK) += ext_process_environment.o
obj-$(V3_CONFIG_EXT_CODE_INJECT) += ext_code_inject.o
obj-$(V3_CONFIG_EXT_ENV_INJECT) += ext_env_inject.o
obj-$(V3_CONFIG_EXT_GUARD_MODULES) += ext_guard_mods.o
obj-$(V3_CONFIG_EXT_PRIV) += ext_priv.o

obj-y += null.o


