obj-$(V3_CONFIG_APIC) += apic.o
obj-$(V3_CONFIG_IO_APIC) += io_apic.o
obj-$(V3_CONFIG_MPTABLE) += mptable.o
obj-$(V3_CONFIG_PIT) += 8254.o
obj-$(V3_CONFIG_PIC) += 8259a.o
obj-$(V3_CONFIG_BOCHS_DEBUG) += bochs_debug.o
obj-$(V3_CONFIG_GENERIC) += generic.o
obj-$(V3_CONFIG_I440FX) += i440fx.o
obj-$(V3_CONFIG_IDE) += ide.o
obj-$(V3_CONFIG_SERIAL_UART) += serial.o

obj-$(V3_CONFIG_KEYBOARD) += keyboard.o
obj-$(V3_CONFIG_LINUX_VIRTIO_BALLOON) += lnx_virtio_balloon.o
obj-$(V3_CONFIG_LINUX_VIRTIO_BLOCK) += lnx_virtio_blk.o
obj-$(V3_CONFIG_LINUX_VIRTIO_SYM) += lnx_virtio_sym.o
obj-$(V3_CONFIG_LINUX_VIRTIO_NET) += lnx_virtio_nic.o
obj-$(V3_CONFIG_LINUX_VIRTIO_VNET) += lnx_virtio_vnet.o
obj-$(V3_CONFIG_LINUX_VIRTIO_CONSOLE) += lnx_virtio_console.o
obj-$(V3_CONFIG_VNET_NIC) += vnet_nic.o
obj-$(V3_CONFIG_NVRAM) += nvram.o
obj-$(V3_CONFIG_OS_DEBUG) += os_debug.o
obj-$(V3_CONFIG_PCI) += pci.o
obj-$(V3_CONFIG_HOST_PCI) += host_pci.o
obj-$(V3_CONFIG_PIIX3) += piix3.o
obj-$(V3_CONFIG_SWAPBYPASS_DISK_CACHE) += swapbypass_cache.o
obj-$(V3_CONFIG_SWAPBYPASS_DISK_CACHE2) += swapbypass_cache2.o
obj-$(V3_CONFIG_DISK_MODEL) += disk_model.o
obj-$(V3_CONFIG_NIC_BRIDGE) += nic_bridge.o

obj-$(V3_CONFIG_NE2K) += ne2k.o
obj-$(V3_CONFIG_RTL8139) += rtl8139.o

obj-$(V3_CONFIG_TMPDISK) += tmpdisk.o
obj-$(V3_CONFIG_RAMDISK) += ramdisk.o 
obj-$(V3_CONFIG_NETDISK) += netdisk.o 
obj-$(V3_CONFIG_FILEDISK) += filedisk.o

obj-$(V3_CONFIG_CGA) += cga.o
obj-$(V3_CONFIG_TELNET_CONSOLE) += telnet_cons.o
obj-$(V3_CONFIG_CURSES_CONSOLE) += curses_cons.o

obj-$(V3_CONFIG_PASSTHROUGH_PCI) += pci_passthrough.o

obj-$(V3_CONFIG_SYMMOD) += lnx_virtio_symmod.o
obj-$(V3_CONFIG_CHAR_STREAM) += char_stream.o

obj-$(V3_CONFIG_VGA) += vga.o


obj-$(V3_CONFIG_VNET_GUEST_IFACE) += vnet_guest_iface.o
