obj-$(CONFIG_APIC) += apic.o
obj-$(CONFIG_PIT) += 8254.o
obj-$(CONFIG_PIC) += 8259a.o
obj-$(CONFIG_BOCHS_DEBUG) += bochs_debug.o
obj-$(CONFIG_GENERIC) += generic.o
obj-$(CONFIG_I440FX) += i440fx.o
obj-$(CONFIG_IDE) += ide.o
obj-$(CONFIG_IO_APIC) += io_apic.o
obj-$(CONFIG_KEYBOARD) += keyboard.o
obj-$(CONFIG_LINUX_VIRTIO_BALLOON) += lnx_virtio_balloon.o
obj-$(CONFIG_LINUX_VIRTIO_BLOCK) += lnx_virtio_blk.o
obj-$(CONFIG_LINUX_VIRTIO_SYM) += lnx_virtio_sym.o
obj-$(CONFIG_NVRAM) += nvram.o
obj-$(CONFIG_OS_DEBUG) += os_debug.o
obj-$(CONFIG_PCI) += pci.o
obj-$(CONFIG_PIIX3) += piix3.o
obj-$(CONFIG_SYM_SWAP) += sym_swap.o

obj-$(CONFIG_NE2K) += ne2k.o

obj-$(CONFIG_TMPDISK) += tmpdisk.o
obj-$(CONFIG_RAMDISK) += ramdisk.o 
obj-$(CONFIG_NETDISK) += netdisk.o 

obj-$(CONFIG_CGA) += cga.o
obj-$(CONFIG_TELNET_CONSOLE) += telnet_cons.o

obj-$(CONFIG_PASSTHROUGH_PCI) += pci_passthrough.o
