obj-y := \
	8254.o \
	8259a.o \
	apic.o \
	bochs_debug.o \
	generic.o \
	i440fx.o \
	ide.o \
	io_apic.o \
	keyboard.o \
	lnx_virtio_balloon.o \
	lnx_virtio_blk.o \
	lnx_virtio_sym.o \
	nvram.o \
	os_debug.o \
	pci.o \
	piix3.o \
	ram_cd.o \
	ram_hd.o \
	sym_swap.o 

#	ne2k.o \

obj-$(CONFIG_SOCKET) += net_cd.o \
			net_hd.o 
