/* MACHINE GENERATED; DO NOT EDIT */
#define VMX_ASSIST_CTX_GS_SEL	0x78
#define VMX_ASSIST_CTX_FS_SEL	0x68
#define VMX_ASSIST_CTX_DS_SEL	0x38
#define VMX_ASSIST_CTX_ES_SEL	0x48
#define VMX_ASSIST_CTX_SS_SEL	0x58
#define VMX_ASSIST_CTX_ESP	0x4
#define VMX_ASSIST_CTX_EFLAGS	0x8
#define VMX_ASSIST_CTX_CS_SEL	0x28
#define VMX_ASSIST_CTX_EIP	0x0
#define VMX_ASSIST_CTX_CR0	0xc
