obj-y += null.o
obj-$(V3_CONFIG_EXT_MTRRS) += ext_mtrr.o
obj-$(V3_CONFIG_EXT_VTSC) += ext_vtsc.o
obj-$(V3_CONFIG_EXT_VTIME) += ext_vtime.o
obj-$(V3_CONFIG_EXT_INSPECTOR) += ext_inspector.o

obj-$(V3_CONFIG_SYSCALL_HIJACK) += vmm_syscall_hijack.o 
obj-$(V3_CONFIG_SYSCALL_HIJACK) += vmm_linux_syscall_map.o
obj-$(V3_CONFIG_SYSCALL_HIJACK) += vmm_mpi_accel.o
obj-$(V3_CONFIG_SYSCALL_HIJACK) += vmm_process_environment.o
obj-$(V3_CONFIG_SYSCALL_HIJACK) += vmm_execve_hook.o
