obj-y += null.o
obj-$(V3_CONFIG_EXT_MTRRS) += ext_mtrr.o
obj-$(V3_CONFIG_EXT_VTSC) += ext_vtsc.o
obj-$(V3_CONFIG_EXT_VTIME) += ext_vtime.o
obj-$(V3_CONFIG_EXT_INSPECTOR) += ext_inspector.o
obj-$(V3_CONFIG_EXT_MACH_CHECK) += ext_mcheck.o
obj-$(V3_CONFIG_EXT_VMWARE) += ext_vmware.o
