#!/usr/bin/perl -w

if ($#ARGV!=0) { 
	print "v3_console /dev/v3-vmXXX\n";
	print "Use '\\' to escape terminal\n\n";
	print "Use v3_cons if you are on a raw PC console\n";
	print "Use vncviewer if you are trying to connect to a v3_vncserver\n";
	exit;
}


$vm=shift;

system "v3_cons_sc $vm 2>/dev/null";

