obj-$(CONFIG_SOCKET) +=  vmm_socket.o
obj-$(CONFIG_PACKET) +=  vmm_packet.o
obj-$(CONFIG_FILE) += vmm_file.o
obj-$(CONFIG_CONSOLE) += vmm_console.o
obj-$(CONFIG_STREAM) += vmm_stream.o
obj-$(CONFIG_GRAPHICS_CONSOLE) += vmm_graphics_console.o
obj-$(CONFIG_KEYED_STREAMS) += vmm_keyed_stream.o


