obj-$(V3_CONFIG_SOCKET) +=  vmm_socket.o
obj-$(V3_CONFIG_PACKET) +=  vmm_packet.o
obj-$(V3_CONFIG_FILE) += vmm_file.o
obj-$(V3_CONFIG_CONSOLE) += vmm_console.o
obj-$(V3_CONFIG_STREAM) += vmm_stream.o
obj-$(V3_CONFIG_GRAPHICS_CONSOLE) += vmm_graphics_console.o
obj-$(V3_CONFIG_KEYED_STREAMS) += vmm_keyed_stream.o
obj-$(V3_CONFIG_HOST_DEVICE) += vmm_host_dev.o
obj-$(V3_CONFIG_HOST_HYPERCALL) += vmm_host_hypercall.o
obj-$(V3_CONFIG_HOST_PCI) += host_pci.o

obj-y += null.o

